CREATE TABLE `IMOVEL_TB` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`tipo` VARCHAR(255) NOT NULL,
	`endereco_id` INTEGER NOT NULL,
	`capacidade` INTEGER NOT NULL,
	`num_quartos` INTEGER NOT NULL,
	`disponibilidade` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `ENDERECO_TB` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`rua` VARCHAR(255),
	`numero` VARCHAR(255),
	`bairro` VARCHAR(255),
	`complemento` VARCHAR(255),
	`cidade` VARCHAR(255),
	`estado` VARCHAR(255),
	`cep` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `QUARTO_TB` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`num_do_quarto` VARCHAR(255) NOT NULL,
	`capacidade` INTEGER NOT NULL,
	`imovel_id` INTEGER NOT NULL,
	`ocupado` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `EQUIPE_TB` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`nome` VARCHAR(255) NOT NULL,
	`num_membros` INTEGER NOT NULL,
	`status_alocacao` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `ALOCACAO_TB` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`equipe_id` INTEGER NOT NULL,
	`quarto_designado_id` INTEGER NOT NULL,
	`imovel_id` INTEGER NOT NULL,
	`data_inicio` DATETIME NOT NULL,
	`data_fim` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `IMOVEL_TB`
ADD FOREIGN KEY(`endereco_id`) REFERENCES `ENDERECO_TB`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `QUARTO_TB`
ADD FOREIGN KEY(`imovel_id`) REFERENCES `IMOVEL_TB`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ALOCACAO_TB`
ADD FOREIGN KEY(`equipe_id`) REFERENCES `EQUIPE_TB`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ALOCACAO_TB`
ADD FOREIGN KEY(`imovel_id`) REFERENCES `IMOVEL_TB`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ALOCACAO_TB`
ADD FOREIGN KEY(`quarto_designado_id`) REFERENCES `QUARTO_TB`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;